[package]
name = "mosler"
version = "0.1.0"
authors = ["Abhijat Malviya <malviya.abhijat@gmail.com>"]

[dependencies]
rustyline = { git = "https://github.com/kkawakam/rustyline" }
reqwest = "0.8"
hyper = "0.11"
serde_derive = "1.0"
serde = "1.0"
